name: publish

on:
  workflow_dispatch:

  push:
    tags:
      - v*

jobs:
  publish:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Write Secrets Info
        run: |
          echo mavenCentralUsername='${{ secrets.OSSRH_USERNAME }}' >> gradle.properties
          echo mavenCentralPassword='${{ secrets.OSSRH_PASSWORD }}' >> gradle.properties
          echo signing.keyId='${{ secrets.OSSRH_GPG_SECRET_KEY_ID }}' >> gradle.properties
          echo signing.password='${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}' >> gradle.properties
          echo signing.secretKeyRingFile='${{ github.workspace }}/secring.gpg' >> gradle.properties
          echo ${{ secrets.OSSRH_GPG_SECRET_FILE_BASE64 }} | base64 --decode > ${{ github.workspace }}/secring.gpg

      - run: chmod 777 ./gradlew

      - name: Publish to Maven Central
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache

  release:
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@v4

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body_path: ./CHANGELOG.md
