name: Publish to Maven Central

on:
  workflow_dispatch:

  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Write Secrets Info
        run: |
          echo mavenCentralUsername='${{ secrets.OSSRH_USERNAME }}' >> gradle.properties
          echo mavenCentralPassword='${{ secrets.OSSRH_PASSWORD }}' >> gradle.properties
          echo signing.keyId='${{ secrets.OSSRH_GPG_SECRET_KEY_ID }}' >> gradle.properties
          echo signing.password='${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}' >> gradle.properties
          echo signing.secretKeyRingFile='${{ github.workspace }}/secring.gpg' >> gradle.properties
          echo ${{ secrets.OSSRH_GPG_SECRET_FILE_BASE64 }} | base64 --decode > ${{ github.workspace }}/secring.gpg

      - run: chmod 777 ./gradlew

      - name: Publish to Maven Central
        run: ./gradlew publishToMavenCentral --no-configuration-cache
